In [1]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [2]:
q1 = "Can I still join the course after the start date?"
v1 = model.encode(q1)

In [3]:
v1

array([ 2.13904120e-02, -7.39799663e-02,  1.42068556e-03,  2.13816613e-02,
        2.45113149e-02,  3.15582752e-02, -1.10839702e-01, -1.05017498e-01,
       -6.18258938e-02, -6.42311852e-03,  3.72399064e-03,  9.06393602e-02,
       -9.49941017e-03,  6.53976873e-02,  1.10946558e-02, -2.10097339e-02,
       -3.35125513e-02, -4.31677327e-02,  9.96348727e-03,  1.41969863e-02,
       -6.40414879e-02, -7.04182126e-03, -7.91188031e-02,  5.80030754e-02,
        1.30212074e-03,  4.19733534e-03,  5.70979156e-02,  6.39447570e-02,
        2.49902904e-02, -3.95876691e-02, -3.79506797e-02,  2.70394552e-02,
        1.79423206e-02,  1.72272157e-02,  3.43311131e-02,  9.29055270e-03,
        5.86054735e-02, -4.97789569e-02, -5.05366083e-03,  4.34328541e-02,
       -1.56622957e-02, -2.97534503e-02, -5.13325352e-03,  5.13414629e-02,
        6.16060290e-03,  6.86980635e-02, -1.29505778e-02, -5.61938696e-02,
       -1.08265011e-02,  5.96683845e-02,  5.29939681e-02, -3.42755206e-02,
       -4.15274203e-02, -

In [4]:
d  = "You don't need to register. You're accepted. You can also just start learning and submitting homework without registering."
dv = model.encode(d)

In [5]:
v1.dot(dv)

np.float32(0.32332397)

In [9]:
from ingest import load_faq_data

documents = load_faq_data()

documents[0]

{'id': '9e508f2212',
 'course': 'data-engineering-zoomcamp',
 'section': 'General Course-Related Questions',
 'question': 'Course: When does the course start?',
 'answer': "A new cohort runs roughly January–April every year. For the current cohort's exact start date and registration link, check the [course repo README](https://github.com/DataTalksClub/data-engineering-zoomcamp).\n\n- Register via the link in the course repo before the cohort starts.\n- Join the [course Telegram channel](https://t.me/dezoomcamp) for announcements.\n- Join DataTalks.Club's [Slack](https://datatalks.club/docs/general/slack/) and the `#course-data-engineering` channel."}

In [10]:
texts = []

for doc in documents:
    text = doc["question"] + " " + doc["answer"]
    texts.append(text)


In [11]:
texts[0]

"Course: When does the course start? A new cohort runs roughly January–April every year. For the current cohort's exact start date and registration link, check the [course repo README](https://github.com/DataTalksClub/data-engineering-zoomcamp).\n\n- Register via the link in the course repo before the cohort starts.\n- Join the [course Telegram channel](https://t.me/dezoomcamp) for announcements.\n- Join DataTalks.Club's [Slack](https://datatalks.club/docs/general/slack/) and the `#course-data-engineering` channel."

In [12]:
from tqdm.auto import tqdm

batch_size = 50
vectors = []

for i in tqdm(range(0, len(texts), batch_size)):
    batch = texts[i:i + batch_size]
    batch_vectors = model.encode(batch)
    vectors.extend(batch_vectors)

len(vectors)

  0%|          | 0/27 [00:00<?, ?it/s]

1350

In [13]:
vectors[0]

array([-2.67062243e-02, -1.22457556e-01,  1.59441810e-02,  6.09419961e-03,
       -1.11915041e-02, -6.55021220e-02, -7.62883872e-02, -2.08820179e-02,
       -9.27567407e-02,  3.55664827e-02,  3.15623023e-02, -1.09017007e-02,
       -2.45336294e-02, -1.82476453e-02,  3.43917273e-02, -1.32052284e-02,
        7.22677913e-03, -1.54126719e-01,  6.41842559e-02, -9.07449145e-03,
        3.94655168e-02, -2.99637597e-02,  2.08512675e-02,  3.71391624e-02,
        3.52526940e-02, -2.49497825e-03,  7.71128982e-02,  2.78048050e-02,
        1.54832490e-02,  4.92821680e-03,  1.48516195e-03,  3.93927470e-02,
        7.25188628e-02,  9.02841091e-02,  5.25653325e-02,  2.72272304e-02,
        3.86085585e-02, -7.50263035e-02, -2.48754397e-02,  1.06018260e-01,
       -4.82870899e-02, -5.00598513e-02, -4.16486375e-02,  7.91618153e-02,
        5.06461747e-02, -3.68613109e-04, -2.83320853e-03, -2.59598717e-02,
       -3.82818393e-02,  8.59545469e-02, -2.85155009e-02, -7.23346546e-02,
       -2.05845572e-02,  

In [14]:
import numpy as np
X = np.array(vectors)
v_query = v1
scores = [v_query.dot(X[i]) for i in range(len(X))]

In [15]:
scores

[np.float32(0.48740578),
 np.float32(0.20991932),
 np.float32(0.76294106),
 np.float32(0.4437854),
 np.float32(0.2608399),
 np.float32(0.48665166),
 np.float32(0.30061564),
 np.float32(0.56009996),
 np.float32(0.4596049),
 np.float32(0.2562817),
 np.float32(0.33153275),
 np.float32(0.27318534),
 np.float32(0.27691638),
 np.float32(0.34123003),
 np.float32(0.46007168),
 np.float32(0.26240283),
 np.float32(0.3920008),
 np.float32(0.10854167),
 np.float32(0.2756731),
 np.float32(0.16646823),
 np.float32(0.31437925),
 np.float32(0.006685449),
 np.float32(0.112050325),
 np.float32(0.21905689),
 np.float32(0.3400085),
 np.float32(0.23571292),
 np.float32(0.32714835),
 np.float32(0.15088356),
 np.float32(0.16563278),
 np.float32(0.05545026),
 np.float32(0.23541194),
 np.float32(0.08533022),
 np.float32(-0.0030899365),
 np.float32(-0.042598385),
 np.float32(-0.06027717),
 np.float32(0.006491054),
 np.float32(0.034277476),
 np.float32(-0.0495897),
 np.float32(-0.0006708354),
 np.float32(-0.0170

In [16]:
#Better performance
scores = []
scores = X.dot(v_query)

In [17]:
scores

array([ 0.48740575,  0.20991933,  0.762941  , ..., -0.08637968,
        0.03759793, -0.03037044], shape=(1350,), dtype=float32)

In [18]:
# Find the index of the highest scoring document
idx = np.argmax(scores)
idx, scores[idx]

documents[idx]

{'id': '3f1424af17',
 'course': 'data-engineering-zoomcamp',
 'section': 'General Course-Related Questions',
 'question': 'Course: Can I still join the course after the start date?',
 'answer': "Yes, even if you don't register, you're still eligible to submit the homework.\n\nBe aware, however, that there will be deadlines for turning in homeworks and the final projects. So don't leave everything for the last minute."}

In [19]:
#Top 5 results
top5 = np.argsort(scores)[-5:]

#Negatiing score
top5 = np.argsort(-scores)[:5]

for idx in top5:
    print(scores[idx])
    print(documents[idx])
    print()

0.762941
{'id': '3f1424af17', 'course': 'data-engineering-zoomcamp', 'section': 'General Course-Related Questions', 'question': 'Course: Can I still join the course after the start date?', 'answer': "Yes, even if you don't register, you're still eligible to submit the homework.\n\nBe aware, however, that there will be deadlines for turning in homeworks and the final projects. So don't leave everything for the last minute."}

0.7579371
{'id': '2d8b16c2a0', 'course': 'mlops-zoomcamp', 'section': 'General Course-Related Questions', 'question': 'Course - Can I still join the course after the start date?', 'answer': "Yes, even if you don't register, you're still eligible to submit the homeworks as long as the form is still open and accepting submissions.\n\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything to the last minute."}

0.7192132
{'id': '41aabbd7c5', 'course': 'machine-learning-zoomcamp', 'section': 'General Course-Related 

In [20]:
from minsearch import VectorSearch

vindex = VectorSearch(keyword_fields=["course"])
vindex.fit(X, documents)

In [21]:
query = "I just discovered the course. Can I still join it?"
query_vector = model.encode(query)

results = vindex.search(query_vector, num_results=5)

In [22]:
results[0]

{'id': '74eb249bbf',
 'course': 'llm-zoomcamp',
 'section': 'General Course-Related Questions',
 'question': 'I just discovered the course. Can I still join?',
 'answer': 'Yes, but if you want to receive a certificate, you need to submit your project while we’re still accepting submissions.'}

In [23]:
results = vindex.search(
    query_vector,
    filter_dict={"course": "llm-zoomcamp"},
    num_results=5
)

In [24]:
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()
openai_client = OpenAI()

In [25]:
from ingest import load_faq_data, build_index

documents = load_faq_data()
index = build_index(documents)

In [26]:
from rag_helper import RAGBase

assistant = RAGBase(
    index=index,
    llm_client=openai_client,
)

ModuleNotFoundError: No module named 'rag_helper'

In [ ]:
query = "I just found out about the program, can I still sign up?"
assistant.rag(query)

'Yes, but if you want to receive a certificate, you need to submit your project while we’re still accepting submissions.'

In [ ]:
class RAGVector(RAGBase):

    def __init__(self, embedder, **kwargs):
        super().__init__(**kwargs)
        self.embedder = embedder

    def search(self, query, num_results=5):
        query_vector = self.embedder.encode(query)
        filter_dict = {"course": self.course}

        return self.index.search(
            query_vector,
            num_results=num_results,
            filter_dict=filter_dict
        )

In [ ]:
vector_assistant = RAGVector(
    embedder=model,
    index=vindex,
    llm_client=openai_client,
)

vector_assistant.rag("the program has already begun, can I still sign up?")

'Yes, you can still join. You can start learning and submitting homework while the form is open, and registration is not checked against a list. If you want a certificate, make sure to submit your project while submissions are still being accepted.'

### SQLlitesearch

In [27]:
from sqlitesearch import VectorSearchIndex

vs_index = VectorSearchIndex(
    keyword_fields=["course"],
    mode="ivf",
    db_path="faq_vectors2.db"
)

In [28]:
vs_index.fit(vectors, documents)

In [29]:
vs_index.close

<bound method VectorSearchIndex.close of <sqlitesearch.vector.index.VectorSearchIndex object at 0x7847509e98b0>>